# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e80584f41c380035a5ef1eee289e164a51590516ab2a5858e4979b3a31b2888f076153438c9eafc3747d1852479c6424df58229579f58f5472670a3cb55270e

test:
  secret_key_base: 40dec069d05cf5c13e5418926406946ff956952a4ed4e0f144bc30115ae29c7ef2e9cf9d34acddf4aa926651d9b9209dbc0a5607b55f858bc24b66a54b97c28b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
